### ISSUE TITLE
Please email me

### ISSUE THREAD

**Issue by matulekpl** [zwartevogel/Panasonic-Aquarea-NodeRed#1]
Hello,
could You please send me nodered file?? 
Here is my email: eomnia@gmail.com

**Comment by spamajor** [comment]
Hi Black-bird, do you want to share the node-red file? Thanx and regards

**Comment by drienties** [comment]
Hi Black-bird,

Would it be possible to share the node-red file.

Kind regards.

**Comment by zwartevogel** [comment]
Script is online now. Sorry for the delay.
btw: check out also https://github.com/IgorYbema/HeishaMon/
