### ISSUE TITLE
Update Panasonic

### ISSUE THREAD

**Issue by BazemanKM** [zwartevogel/Panasonic-Aquarea-NodeRed#4]
Getting errors in Node-Red:

30-3-2020 12:30:05node: Prepare select gwidfunction : (error)
"TypeError: Cannot read property '0' of undefined"
30-3-2020 12:31:04node: Get data fieldsfunction : (error)
"TypeError: Cannot read property 'function-status-text-007' of undefined"

**Comment by QHose** [comment]
Do we need to use the JSESSIONID now? Did pana change the authenticaton/session management?

**Comment by supersjimmie** [comment]
I think I got that same error.
See https://github.com/zwartevogel/Panasonic-Aquarea-NodeRed/issues/5 where I solved it for me.
